# Generated by Django 5.0.1 on 2024-02-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_db',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='signup_db',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signup_db',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
