# Generated by Django 5.0.1 on 2024-02-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes_app', '0002_alter_signup_db_email_alter_signup_db_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Panel_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50, null=True)),
                ('recipe_dscription', models.TextField(null=True)),
                ('recipe_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
